apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app1-rs
  namespace: app1-ns
  labels:
    environment: dev
    application: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: dev
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80