---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-stage-deployment
  namespace: apache-stage
  labels:
    app: apache
    env: stage
    team: infra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
      env: stage
  template:
    metadata:
      labels:
        name: apache-stage
        app: apache
        env: stage
    spec:
      containers:
      - name: apache
        image: httpd:2.4.53
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "100m"