---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-dev-deployment
  namespace: apache-dev
  labels:
    app: apache
    env: dev
    team: infra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
      env: dev
  template:
    metadata:
      labels:
        name: apache-dev
        app: apache
        env: dev
    spec:
      containers:
      - name: apache
        image: httpd:2.4.53
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "100m"